name: Go

on: 
  workflow_dispatch:
    inputs:
      manualTag:
        description: 'Which tag to build?'  

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with: 
        ref: refs/tags/${{ github.event.inputs.manualTag }}"

    - name: Build
      run: ./build.sh
    
    - name: Test
      run: ./main

