name: Manual Go Build

on: 
  workflow_dispatch:
    inputs:
      tagManual:
        description: 'Which tag to build?' 
        required: true
        default: "v1.6"  

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code
      uses: actions/checkout@v2
      with: 
        ref: refs/tags/${{ github.event.inputs.tagManual }}

    - name: Build
      run: |
        #!/usr/bin/env bash
        # This command can print name in this priority: tag > branch > commit
        version=$(git describe --tags --exact-match 2> /dev/null \
          || git symbolic-ref -q --short HEAD \
          || git rev-parse --short HEAD)

        export VERSION=$version
        echo "$VERSION"

        go build -ldflags "-X main.version=$VERSION" -o main
    
    - name: Test
      run: ./main
