name: Docker Build Manual

on: 
  workflow_dispatch:
    inputs:
      tagManual:
        description: 'Which tag to build?'
        required: true
        default: "v1.6" 

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      image_name: "vensder/github-actions-tag-build"
      image_tag: "${{ github.event.inputs.tagManual }}"

    steps:
    - name: Extract workflow branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: workflow_branch

    - name: Check out ${{ env.image_tag }} tag to build
      uses: actions/checkout@v2
      with: 
        ref: refs/tags/${{ env.image_tag }}

    - name: Check out ${{ steps.workflow_branch.outputs.branch }} branch for Dockerfile and build script
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
        path: main_branch    

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Copy Dockerfile and script from ${{ steps.workflow_branch.outputs.branch }} branch
      run: |
        cp main_branch/Dockerfile.manual Dockerfile
        cp main_branch/build_manual.sh build.sh

    - name: Build and push docker image from ${{ env.image_tag }} tag sources
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        tags: ${{ env.image_name }}:${{ env.image_tag }}
        load: true

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}

    - name: Push
      run: docker push $image_name:$image_tag

    # - name: Test docker container
    #   run: docker run $image_name:$image_tag

