name: Docker Build Manual

on: 
  workflow_dispatch:
    inputs:
      manualTag:
        description: 'Which tag to build?'
        required: true
        default: "v1.6" 

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      image_name: "vensder/github-actions-tag-build"
      version: "${{ github.event.inputs.manualTag }}"

    steps:
    - name: Check out the ${{ github.event.inputs.manualTag }} tag to build
      uses: actions/checkout@v2
      with: 
        ref: refs/tags/${{ github.event.inputs.manualTag }}

    - name: Check out the ${{ github.ref }} branch for Dockerfile and build script
      uses: actions/checkout@v2
      with:
        ref: ${{github.ref}}
        path: main_branch    

    - name: Build docker image from ${{ github.event.inputs.manualTag }} tag sources
      run: |
        cp main_branch/Dockerfile.manual Dockerfile
        cp main_branch/build_manual.sh build.sh
        docker build . --file Dockerfile --tag $image_name:$version

    - name: Test docker container
      run: docker run $image_name:$version

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push docker image
      run: docker push $image_name:$version
