name: Manual Docker Build

on: 
  workflow_dispatch:
    inputs:
      manualTag:
        description: 'Which tag to build?'  

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      image_name: "vensder/github-actions-tag-build"
      version: "${{github.event.inputs.manualTag}}"

    steps:
    - name: Check out the tag
      uses: actions/checkout@v2
      with: 
        ref: refs/tags/${{github.event.inputs.manualTag}}
    
    - name: Create build script
      run: |
        cat > build.sh << EOF
        #!/usr/bin/env bash
        set -e
        set -x
        go build -ldflags "-X main.version=$version" -o main
        EOF

        chmod +x ./build.sh
        cat ./build.sh

    - name: Create Dockerfile
      run: |
        cat > Dockerfile << EOF
        FROM golang:1.14 AS build
        WORKDIR /src
        COPY . .
        RUN ./build.sh
        FROM scratch AS bin
        COPY --from=build /src/main /
        CMD [ "/main" ]
        EOF

        cat Dockerfile

    - name: Build docker image
      run: docker build . --file Dockerfile --tag $image_name:$version

    - name: Test docker container
      run: docker run $image_name:$version

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push docker image
      run: docker push $image_name:$version
