name: Docker Build Manual

on: 
  workflow_dispatch:
    inputs:
      tagManual:
        description: 'Which tag to build?'
        required: true
        default: "v1.6" 

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      image_name: "vensder/github-actions-tag-build"
      version: "${{ github.event.inputs.tagManual }}"

    steps:
    - name: Check out the ${{ github.event.inputs.tagManual }} tag to build
      uses: actions/checkout@v2
      with: 
        ref: refs/tags/${{ github.event.inputs.tagManual }}

    - name: Check out the ${{ github.ref }} branch for Dockerfile and build script
      uses: actions/checkout@v2
      with:
        ref: ${{github.ref}}
        path: main_branch    

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Copy Dockerfile and script from the ${{ github.ref }} branch
      run: |
        cp main_branch/Dockerfile.manual Dockerfile
        cp main_branch/build_manual.sh build.sh
        # docker build . --file Dockerfile --tag $image_name:$version

    - name: Build and push the docker image from the ${{ github.event.inputs.tagManual }} tag sources
      # id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        # push: true
        # ${{ env.REGISTRY }}/myapp:latest
        tags: vensder/github-actions-tag-build:${{ env.version }}
        load: true


    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}

    - name: Push
      run: docker push vensder/github-actions-tag-build:latest

    # - name: Test docker container
    #   run: docker run $image_name:$version

    # - name: Login to DockerHub
    #   uses: docker/login-action@v1
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}

    # - name: Push docker image
    #   run: docker push $image_name:$version
