name: Go Build Manual

on: 
  workflow_dispatch:
    inputs:
      tagManual:
        description: 'Which tag to build?' 
        required: true
        default: "v1.6"  

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out ${{ github.event.inputs.tagManual }} tag code
      uses: actions/checkout@v2
      with: 
        ref: refs/tags/${{ github.event.inputs.tagManual }}

    - name: Check out the ${{ github.ref }} branch for build script
      uses: actions/checkout@v2
      with:
        ref: ${{github.ref}}
        path: main_branch   

    - name: Build ${{ github.event.inputs.tagManual }} tag
      run: ./main_branch/build_manual.sh
    
    - name: Test the binary
      run: ./app
