name: Manual Docker Build

on: 
  workflow_dispatch:
    inputs:
      manualTag:
        description: 'Which tag to build?'  

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      image_name: "vensder/github-actions-tag-build"
      version: "${{github.event.inputs.manualTag}}"

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with: 
        ref: "refs/tags/$version"
    
    - name: Create build script
      run: |
        cat > build.sh << EOF
        #!/usr/bin/env bash
        set -e
        set -x

        go build -ldflags "-X main.version=$version" -o main
        EOF

        chmod +x ./build.sh
        cat ./build.sh

    - name: Create Dockerfile
      run: |
        cat > Dockerfile << EOF
        FROM golang:1.14 AS build
        WORKDIR /src
        COPY . .
        RUN ./build.sh
        FROM scratch AS bin
        COPY --from=build /src/main /
        CMD [ "/main" ]
        EOF

        cat Dockerfile

    - name: Build and test docker image
      run: |
        docker build . --file Dockerfile --tag $image_name:$version
        docker run $image_name:$version

